logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
sharefileroot: "E:\\logs"
download_tmproot: "E:\\logss\\download"

spring:
  servlet:
    multipart:
      maxFileSize: "1000MB"
      maxRequestSize: "10000MB"

server:
  port: 8080